# Generated by Django 4.1.7 on 2023-03-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_paid', models.CharField(max_length=255)),
                ('order_date', models.DateField()),
                ('payment_type', models.CharField(max_length=255)),
            ],
        ),
    ]
