# Generated by Django 4.1.7 on 2023-03-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_item_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_order',
            name='line_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item_order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
