# Generated by Django 4.1.7 on 2023-03-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_item_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='stock',
            new_name='stock_quantity',
        ),
    ]
