# Generated by Django 4.1.7 on 2023-03-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_rename_stock_item_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_quantity',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
